apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-application
  labels:
    app: sample-application
spec:
  selector:
    matchLabels:
      app: sample-application
  template:
    metadata:
      labels:
        app: sample-application
    spec:
      containers:
      - name: web
        image: "sadovnikov/sample-app:{{ .Values.version }}"
        ports:
        - containerPort: 8080
