kind: Service
apiVersion: v1
metadata:
  name: sample-application
  labels:
    app: sample-application
spec:
  selector:
    app: sample-application
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
