kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.application }}
  labels:
    app: {{ .Values.application }}
spec:
  selector:
    app: {{ .Values.application }}
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
